import { Button, Input, Radio, Text, Title } from "@mantine/core";
import Head from "next/head";
import { useState } from "react";
import Overline from "../components/globals/Overline";
import Paragraph from "../components/globals/Paragraph";
import Subtitle from "../components/globals/Subtitle";
import RightArrow from "../icons/RightArrow";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [checked, setChecked] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title order={1}>This is h1 title</Title>
        <Radio className="a" checked={checked} onChange={(event) => setChecked(!checked)} />
        <Paragraph>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, quia.</Paragraph>
        <Overline>ahmed</Overline>
        <Subtitle>ahmed</Subtitle>
        <Button>ahmed</Button>
        <Button variant="subtle" rightIcon={<RightArrow />}>
          subtle button
        </Button>
        <Button variant="outline">outline button</Button>
      </main>
    </div>
  );
}
